// Generated by gencpp from file imu_communication/Num.msg
// DO NOT EDIT!


#ifndef IMU_COMMUNICATION_MESSAGE_NUM_H
#define IMU_COMMUNICATION_MESSAGE_NUM_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace imu_communication
{
template <class ContainerAllocator>
struct Num_
{
  typedef Num_<ContainerAllocator> Type;

  Num_()
    : accX(0.0)
    , accY(0.0)  {
    }
  Num_(const ContainerAllocator& _alloc)
    : accX(0.0)
    , accY(0.0)  {
  (void)_alloc;
    }



   typedef double _accX_type;
  _accX_type accX;

   typedef double _accY_type;
  _accY_type accY;





  typedef boost::shared_ptr< ::imu_communication::Num_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::imu_communication::Num_<ContainerAllocator> const> ConstPtr;

}; // struct Num_

typedef ::imu_communication::Num_<std::allocator<void> > Num;

typedef boost::shared_ptr< ::imu_communication::Num > NumPtr;
typedef boost::shared_ptr< ::imu_communication::Num const> NumConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::imu_communication::Num_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::imu_communication::Num_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::imu_communication::Num_<ContainerAllocator1> & lhs, const ::imu_communication::Num_<ContainerAllocator2> & rhs)
{
  return lhs.accX == rhs.accX &&
    lhs.accY == rhs.accY;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::imu_communication::Num_<ContainerAllocator1> & lhs, const ::imu_communication::Num_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace imu_communication

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::imu_communication::Num_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::imu_communication::Num_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::imu_communication::Num_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::imu_communication::Num_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::imu_communication::Num_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::imu_communication::Num_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::imu_communication::Num_<ContainerAllocator> >
{
  static const char* value()
  {
    return "40ec70ad81cadc0ffcb5889fcacbbff8";
  }

  static const char* value(const ::imu_communication::Num_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x40ec70ad81cadc0fULL;
  static const uint64_t static_value2 = 0xfcb5889fcacbbff8ULL;
};

template<class ContainerAllocator>
struct DataType< ::imu_communication::Num_<ContainerAllocator> >
{
  static const char* value()
  {
    return "imu_communication/Num";
  }

  static const char* value(const ::imu_communication::Num_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::imu_communication::Num_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 accX\n"
"float64 accY\n"
"\n"
"\n"
"\n"
;
  }

  static const char* value(const ::imu_communication::Num_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::imu_communication::Num_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.accX);
      stream.next(m.accY);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Num_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::imu_communication::Num_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::imu_communication::Num_<ContainerAllocator>& v)
  {
    s << indent << "accX: ";
    Printer<double>::stream(s, indent + "  ", v.accX);
    s << indent << "accY: ";
    Printer<double>::stream(s, indent + "  ", v.accY);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IMU_COMMUNICATION_MESSAGE_NUM_H
